# This is a basic workflow to help you get started with Actions
name: First Workflow
on: workflow_dispatch
jobs:
 first-job:
   runs-on: ubuntu-latest
   steps:
     - name: print greeting
       run: echo "Hello world"
     - name: print goodbye  
       run: echo "Good-Bye !"
